from __future__ import annotations

from io import StringIO
from typing import Any


def build_html_report(results: dict[str, Any]) -> str:
    summary = results["summary"]
    logs = "".join(f"<li>{m}</li>" for m in results.get("logs", []))
    return f"""<!doctype html>
<html>
<head>
  <meta charset='utf-8' />
  <title>24-7 Carbon Report</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 24px; }}
    table {{ border-collapse: collapse; }}
    td, th {{ border: 1px solid #ccc; padding: 6px 8px; }}
  </style>
</head>
<body>
  <h1>Simulation Report</h1>
  <h2>Summary</h2>
  <table>
    <tr><th>Metric</th><th>Value</th></tr>
    {''.join(f'<tr><td>{k}</td><td>{v}</td></tr>' for k, v in summary.items())}
  </table>
  <h2>Logs</h2>
  <ul>{logs}</ul>
  <p>Generated by 24-7 Carbon demo tool. Defaults are illustrative unless replaced with authoritative inputs.</p>
</body>
</html>"""


def csv_text(rows: list[dict]) -> str:
    import pandas as pd

    buf = StringIO()
    pd.DataFrame(rows).to_csv(buf, index=False)
    return buf.getvalue()
